### PR TITLE
feat: support ELASTICSEARCH_CA_PATH variable

### PR DESCRIPTION
**Pull request by gabor-boros**
This PR allows operators to define custom CA certificates for production instances for environments in which self-signed certificates are created for Elasticsearch. Since `dockerize` cannot be overridden, this change cannot be done in a plugin. This PR is on the borderline of implementing custom CA certificates feature [supported by forum](https://github.com/openedx/cs_comments_service/pull/404) and a bug fix, though I lean towards the bug fix.

The changes include some styling-related modifications in order to have consistency in the file, if needed, I can revert that.

_The contributing guide says, “Before addressing anything other than clear-cut bugs, start a discussion on the [official Open edX forum](https://discuss.openedx.org/).”. I believe it is a clear-cut “bug” that tutor-forum is not supporting custom CA certs, while the forum itself does._

### CODE REVIEW

**Comment by gabor-boros** [comment]
@ghassanmas get better soon!

Thanks for taking a look. It is not urgent, though as it is open for almost a month, it blocks other PRs in the large instances working group.

**Comment by ghassanmas** [comment]
@gabor-boros can you link to any of those PRs, taking a looking to relevant PRs that does have related context might help understand better what does this PR do, otherwise and meanwhile I would have to dig into ES...

Also in regard of 
> _I believe it is a clear-cut “bug” that tutor-forum is not supporting custom CA certs, while the forum itself does._

Do others plugin support that ? I couldn't find any use of `ELASTICSEARCH_CA_PATH ` hence this result https://github.com/search?q=org%3Aoverhangio%20ELASTICSEARCH_CA_PATH&type=code only leads to this PR 

I only finds reference for this in upstream cs_comments_service 

https://github.com/openedx/cs_comments_service/blob/8626d44a6322a813e8c58140b8b2f3039735709c/config/application.yml#L11-L16

```
> <% if ENV['ELASTICSEARCH_CA_PATH'] %>
> elasticsearch_transport_options:
>   ssl:
>     ca_file: <%= ENV['ELASTICSEARCH_CA_PATH'] %>
> <% else %>
> elasticsearch_transport_options: {}

```

**Comment by gabor-boros** [comment]
@ghassanmas Sure, I can link some PRs and issues (which would be resolved by the linked PR):

- https://github.com/openedx/openedx-k8s-harmony/pull/73
- https://github.com/openedx/openedx-k8s-harmony/issues/48
- https://github.com/openedx/openedx-k8s-harmony/issues/23

You may want to get more context, by checking the following PR:

- https://github.com/openedx/openedx-k8s-harmony/pull/13


> Do others plugin support that?

I don't think so, but other plugins are not interacting with forum either, so this is the plugin that should support this.

> I only finds reference for this in upstream cs_comments_service

That's right. Since the code is living in the forum, that should have the variable set.

> Also lastly in regard of testing, does the cert file has to live inside the image? it's clear that when/if opereator needs to utilize thise feature/change they needs to rebuild the image, e.g. tutor images build forum, wonder if there would be a way around this without rebuilding the image... or at least clear inscturetion of the steps to do that, if not just for me for adding to README.rst afterword.

No, the image is not containing the certificates. The certificate is/should be mounted to the container as a read-only volume, so the certificates cannot be altered from within the container. Yes, I know this could be done by `chmod`-ing the certificates after baking them into the Docker image, but that would make the life of operators harder. Especially if the edX instance is running in Kubernetes.

To be honest, I don't really get the second part of the paragraph. In the suggested implementation, we only set a path to the certificate. Sure, the image should be rebuilt if the path changes (i.e., set or unset), but that shouldn't be an issue? Any configuration change (that affects the application) requires an image rebuild. This is no different.

> [...] clear inscturetion of the steps to do that, if not just for me for adding to README.rst afterword .

Hm, that's a good point. I just extended the README and added the new config option too as that was missing.

**Comment by gabor-boros** [comment]
Hey @ghassanmas, did you have a chance to check my comment above?

**Comment by DawoudSheraz** [comment]
@ghassanmas Hi, checking-in on the review of this PR. Thanks

**Comment by gabor-boros** [comment]
Hey @regisb, are you a contributor of this report as well? May I ask for a review? It would be great to have this and all related PRs merged 😇

**Comment by regisb** [comment]
Hi,
I see a couple issues with this PR. In order of increasing importance:

1. Added configuration setting and complexity, for a feature that few people need.
2. Changing the `FORUM_ELASTICSEARCH_CA_PATH` requires re-building the Docker image, which is not a great pattern to follow. I know that there are some Tutor settings for which this is the case (notably: `EDX_PLATFORM_REPOSITORY`, `EDX_PLATFORM_VERSION`) but we should really try to avoid this as much as possible. Image building is a pain, we don't want to ask people to do that too often.
3. If we start supporting custom CA certificates for Elasticsearch in the forum plugin, then we need to also support it in the openedx image from tutor core. Unless I'm mistaken, this feature will not work until a corresponding change is also made in tutor core.

Instead, I suggest adding the Elasticsearch certificates to the standard certs directory -- I think it's /etc/ssl/certs/? This can be done either at build- (with COPY) or run-time (with bind-mounts), depending on your preference. Did you already try this out? If yes, what didn't work?

**Comment by gabor-boros** [comment]
Hey @regisb,

I'm on holiday and from mobile so my options are limited to answer,but:

- The change is working perfectly without modifying the tutor-core as this is solely needed for the dockerize command to function as wanted. See the review comments on the related PRs.
- The forum already supports the custom certificate path, so I'm not sure why it would be a big complexity for the dedicated/corresponding tutor plugin. Especially if it is only needed for the dockerize command
- The certificate could be mounted to the SSL certs directory, however that won't be enough AFAIK. We would need to "re-compile" all certificates in the given directory so the SSL lib is aware of it. If no certificates are added as an extra, that would be an unnecessary step in the docker file that can cause confusion.

I don't like the fact that we have to update tutor-forum, but spent many hours to work it around as simple as possible and couldn't find a simpler solution. However, I'm opened to new options too!

**Comment by regisb** [comment]
OK I understand now. I had not realized that only the call to `dockerize` was causing an issue. It means that if we somehow got rid of dockerize your problem would be resolved, right? That tool always felt like a sub-optimal shim to me. Ideally, we would have a forum native CLI tool that would load the same Elasticsearch (and mongodb) connection parameters as the forum app to test the connection. The fact that we are relying on a separate tool means that we have to duplicate the parameters that are included in the forum app.

Assuming we got rid of dockerize, would that resolve your issue?

**Comment by gabor-boros** [comment]
@regisb assuming dockerize is removed, there would be no need for this PR as I recall.

**Comment by ghassanmas** [comment]
removing `dockerize` might would resolve #39 as well, I think.

**Comment by gabor-boros** [comment]
@regisb how could we unblock this PR? It is blocking several other things and is open for almost 3 months.

**Comment by ghassanmas** [comment]
@gabor-boros could you try if #40 would resolve it, since you mention `dockerize` could be the problem

**Comment by gabor-boros** [comment]
Removing in favor of https://github.com/overhangio/tutor-forum/pull/41

**Pull request closed without merging**
