### PR TITLE
feat: bump version to 16.0.1

### PR DESCRIPTION
**Pull request by Ian2012**
## Description

This PR bumps version to support the latest changes to `cs_comment_service`: https://github.com/openedx/cs_comments_service/compare/open-release/palm.2...master

Mainly this PR: https://github.com/openedx/cs_comments_service/pull/415

### CODE REVIEW

**Review by regisb — CHANGES_REQUESTED** [review]
Sounds reasonable. But this should be a backward-compatible change, so the new version should be 16.0.1. 

Also, please add a changelog entry in CHANGELOG.md and collect existing entries with `scriv collect`.

**Review by regisb — APPROVED** [review]
LGTM! All you need to do is to change the title of your commit to "v16.0.1".

**Comment by Ian2012** [comment]
@regisb ready, thanks for the prompt review

**Review by regisb — APPROVED** [review]
lgtm!

**Comment by Ian2012** [comment]
@regisb although the new image has been pushed, it still references an old commit https://github.com/openedx/cs_comments_service/tree/1f0f0568f001dd9a5be483702dd41c1f40453a60

Can you rebuild the image?

**Comment by regisb** [comment]
I think there was a misunderstanding. The forum image will always reference the open-release/palm.2 tag, not the open-release/palm.master branch. The reason for that is that builds need to be reproducible. If you want to add extra commits to the cs_comments_service repo in the forum image, then you should either:

1. Cherry-pick these changes, as it is being done for edx-platform in the openedx image.
2. Wait for the open-release/palm.3 tag, which should be created very soon.

**Pull request merged**
